services:
  app:
    build: .
    container_name: app
    ports:
      - "8080:${SERVER_PORT}"
    environment:
      - DB_HOST=${DB_HOST}
      - DB_USER_NAME=${DB_USER_NAME}
      - DB_USER_PASSWORD=${DB_USER_PASSWORD}
      - DB_NAME=${DB_NAME}
      - DB_PORT=${DB_PORT}
      - SERVER_PORT=${SERVER_PORT}
      - REDIS_HOST=${REDIS_HOST}
      - REDIS_PORT=${REDIS_PORT}
    tty: true
    depends_on:
      - db
      - redis

  db:
    image: postgres:15
    container_name: postgres_db
    ports:
      - "5432:${DB_PORT}"
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER_NAME}
      POSTGRES_PASSWORD: ${DB_USER_PASSWORD}
      TZ: Asia/Tokyo
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./db/schema:/docker-entrypoint-initdb.d
    restart: always
    tty: true

  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:${REDIS_PORT}"
    restart: always
    tty: true

volumes:
  postgres_data:
    driver: local
