// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package sqlcgen

import (
	"database/sql"
)

type Artist struct {
	ID   int32
	Name string
	Kana string
}

type Chart struct {
	ID             int32
	SongID         sql.NullInt32
	DifficultyType sql.NullInt32
	Level          sql.NullInt32
	ChartViewLink  sql.NullString
}

type Singer struct {
	ID   int32
	Name string
}

type Song struct {
	ID            int32
	Name          string
	Kana          string
	LyricsID      sql.NullInt32
	MusicID       sql.NullInt32
	ArrangementID sql.NullInt32
	Thumbnail     sql.NullString
	OriginalVideo sql.NullString
	ReleaseTime   sql.NullTime
	Deleted       sql.NullBool
}

type SongMusicVideoType struct {
	ID             int32
	SongID         sql.NullInt32
	MusicVideoType sql.NullInt32
}

type Unit struct {
	ID   int32
	Name string
}

type VocalPattern struct {
	ID     int32
	SongID sql.NullInt32
	Name   sql.NullString
}

type VocalPatternSinger struct {
	ID             int32
	VocalPatternID sql.NullInt32
	SingerID       sql.NullInt32
	Position       sql.NullInt32
}

type VocalPatternUnit struct {
	ID             int32
	VocalPatternID sql.NullInt32
	UnitID         sql.NullInt32
}
