// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package sqlcgen

import (
	"database/sql"

	"github.com/google/uuid"
)

type Artist struct {
	ID   int32
	Name string
	Kana string
}

type Chart struct {
	ID             int32
	SongID         sql.NullInt32
	DifficultyType sql.NullInt32
	Level          sql.NullInt32
	ChartViewLink  sql.NullString
}

type MyList struct {
	ID        int32
	UserID    uuid.NullUUID
	Name      string
	Position  int32
	CreatedAt sql.NullTime
	UpdatedAt sql.NullTime
}

type MyListChart struct {
	ID        int32
	MyListID  sql.NullInt32
	ChartID   sql.NullInt32
	ClearType sql.NullInt32
	Memo      sql.NullString
	CreatedAt sql.NullTime
	UpdatedAt sql.NullTime
}

type MyListChartAttachment struct {
	ID             int32
	MyListChartID  sql.NullInt32
	AttachmentType sql.NullInt32
	FileUrl        sql.NullString
	Caption        sql.NullString
	CreatedAt      sql.NullTime
}

type Singer struct {
	ID   int32
	Name string
}

type Song struct {
	ID            int32
	Name          string
	Kana          string
	LyricsID      sql.NullInt32
	MusicID       sql.NullInt32
	ArrangementID sql.NullInt32
	Thumbnail     sql.NullString
	OriginalVideo sql.NullString
	ReleaseTime   sql.NullTime
	Deleted       sql.NullBool
}

type SongMusicVideoType struct {
	ID             int32
	SongID         sql.NullInt32
	MusicVideoType sql.NullInt32
}

type SongUnit struct {
	ID     int32
	SongID sql.NullInt32
	UnitID sql.NullInt32
}

type Unit struct {
	ID   int32
	Name string
}

type User struct {
	ID        uuid.UUID
	Email     string
	Password  string
	CreatedAt sql.NullTime
	UpdatedAt sql.NullTime
	DeletedAt sql.NullTime
}

type VocalPattern struct {
	ID     int32
	SongID sql.NullInt32
	Name   sql.NullString
}

type VocalPatternSinger struct {
	ID             int32
	VocalPatternID sql.NullInt32
	SingerID       sql.NullInt32
	Position       sql.NullInt32
}
