// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: song_music_video_type.sql

package sqlcgen

import (
	"context"
	"database/sql"
)

const insertSongMusicVideoType = `-- name: InsertSongMusicVideoType :one
INSERT INTO song_music_video_types (song_id, music_video_type)
VALUES ($1, $2)
RETURNING id, song_id, music_video_type
`

type InsertSongMusicVideoTypeParams struct {
	SongID         sql.NullInt32
	MusicVideoType sql.NullInt32
}

func (q *Queries) InsertSongMusicVideoType(ctx context.Context, arg InsertSongMusicVideoTypeParams) (SongMusicVideoType, error) {
	row := q.db.QueryRowContext(ctx, insertSongMusicVideoType, arg.SongID, arg.MusicVideoType)
	var i SongMusicVideoType
	err := row.Scan(&i.ID, &i.SongID, &i.MusicVideoType)
	return i, err
}
