// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: song_music_video_type.sql

package sqlcgen

import (
	"context"
	"database/sql"
)

const insertSongMusicVideoTypes = `-- name: InsertSongMusicVideoTypes :exec
INSERT INTO song_music_video_types (song_id, music_video_type)
VALUES ($1, $2)
`

type InsertSongMusicVideoTypesParams struct {
	SongID         sql.NullInt32
	MusicVideoType sql.NullInt32
}

func (q *Queries) InsertSongMusicVideoTypes(ctx context.Context, arg InsertSongMusicVideoTypesParams) error {
	_, err := q.db.ExecContext(ctx, insertSongMusicVideoTypes, arg.SongID, arg.MusicVideoType)
	return err
}
