// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: user.sql

package sqlcgen

import (
	"context"
	"database/sql"

	"github.com/google/uuid"
)

const existsUserByEmail = `-- name: ExistsUserByEmail :one
SELECT EXISTS (
  SELECT 1 FROM users WHERE email = $1
) AS exists
`

func (q *Queries) ExistsUserByEmail(ctx context.Context, email string) (bool, error) {
	row := q.db.QueryRowContext(ctx, existsUserByEmail, email)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const existsUserByID = `-- name: ExistsUserByID :one
SELECT EXISTS (
  SELECT 1 FROM users WHERE id = $1
) AS exists
`

func (q *Queries) ExistsUserByID(ctx context.Context, id uuid.UUID) (bool, error) {
	row := q.db.QueryRowContext(ctx, existsUserByID, id)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT id, email, password, is_verified, verify_token, token_expires_at, is_admin, created_at, updated_at, deleted_at FROM users WHERE email = $1
`

func (q *Queries) GetUserByEmail(ctx context.Context, email string) (User, error) {
	row := q.db.QueryRowContext(ctx, getUserByEmail, email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Password,
		&i.IsVerified,
		&i.VerifyToken,
		&i.TokenExpiresAt,
		&i.IsAdmin,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getUserByID = `-- name: GetUserByID :one
SELECT id, email, password, is_verified, verify_token, token_expires_at, is_admin, created_at, updated_at, deleted_at FROM users WHERE id = $1
`

func (q *Queries) GetUserByID(ctx context.Context, id uuid.UUID) (User, error) {
	row := q.db.QueryRowContext(ctx, getUserByID, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Password,
		&i.IsVerified,
		&i.VerifyToken,
		&i.TokenExpiresAt,
		&i.IsAdmin,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const insertUser = `-- name: InsertUser :one
INSERT INTO users (id, email, password, is_verified, verify_token, token_expires_at, is_admin, created_at, updated_at, deleted_at)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10)
RETURNING id, email, password, is_verified, verify_token, token_expires_at, is_admin, created_at, updated_at, deleted_at
`

type InsertUserParams struct {
	ID             uuid.UUID
	Email          string
	Password       string
	IsVerified     sql.NullBool
	VerifyToken    sql.NullString
	TokenExpiresAt sql.NullTime
	IsAdmin        sql.NullBool
	CreatedAt      sql.NullTime
	UpdatedAt      sql.NullTime
	DeletedAt      sql.NullTime
}

func (q *Queries) InsertUser(ctx context.Context, arg InsertUserParams) (User, error) {
	row := q.db.QueryRowContext(ctx, insertUser,
		arg.ID,
		arg.Email,
		arg.Password,
		arg.IsVerified,
		arg.VerifyToken,
		arg.TokenExpiresAt,
		arg.IsAdmin,
		arg.CreatedAt,
		arg.UpdatedAt,
		arg.DeletedAt,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Password,
		&i.IsVerified,
		&i.VerifyToken,
		&i.TokenExpiresAt,
		&i.IsAdmin,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const isAdminByID = `-- name: IsAdminByID :one
SELECT is_admin FROM users WHERE id = $1
`

func (q *Queries) IsAdminByID(ctx context.Context, id uuid.UUID) (sql.NullBool, error) {
	row := q.db.QueryRowContext(ctx, isAdminByID, id)
	var is_admin sql.NullBool
	err := row.Scan(&is_admin)
	return is_admin, err
}

const isVerifiedByID = `-- name: IsVerifiedByID :one
SELECT is_verified FROM users WHERE id = $1
`

func (q *Queries) IsVerifiedByID(ctx context.Context, id uuid.UUID) (sql.NullBool, error) {
	row := q.db.QueryRowContext(ctx, isVerifiedByID, id)
	var is_verified sql.NullBool
	err := row.Scan(&is_verified)
	return is_verified, err
}

const listUsers = `-- name: ListUsers :many
SELECT id, email, password, is_verified, verify_token, token_expires_at, is_admin, created_at, updated_at, deleted_at FROM users ORDER BY id
`

func (q *Queries) ListUsers(ctx context.Context) ([]User, error) {
	rows, err := q.db.QueryContext(ctx, listUsers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []User
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.ID,
			&i.Email,
			&i.Password,
			&i.IsVerified,
			&i.VerifyToken,
			&i.TokenExpiresAt,
			&i.IsAdmin,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const softDeleteUser = `-- name: SoftDeleteUser :exec
UPDATE users
SET deleted_at = $1,
    updated_at = $2
WHERE id = $3
`

type SoftDeleteUserParams struct {
	DeletedAt sql.NullTime
	UpdatedAt sql.NullTime
	ID        uuid.UUID
}

func (q *Queries) SoftDeleteUser(ctx context.Context, arg SoftDeleteUserParams) error {
	_, err := q.db.ExecContext(ctx, softDeleteUser, arg.DeletedAt, arg.UpdatedAt, arg.ID)
	return err
}

const updateUserEmail = `-- name: UpdateUserEmail :exec
UPDATE users
SET email = $1,
    updated_at = $2
WHERE id = $3
`

type UpdateUserEmailParams struct {
	Email     string
	UpdatedAt sql.NullTime
	ID        uuid.UUID
}

func (q *Queries) UpdateUserEmail(ctx context.Context, arg UpdateUserEmailParams) error {
	_, err := q.db.ExecContext(ctx, updateUserEmail, arg.Email, arg.UpdatedAt, arg.ID)
	return err
}

const updateUserIsVerified = `-- name: UpdateUserIsVerified :exec
UPDATE users
SET is_verified = $1,
    updated_at = $2
WHERE id = $3
`

type UpdateUserIsVerifiedParams struct {
	IsVerified sql.NullBool
	UpdatedAt  sql.NullTime
	ID         uuid.UUID
}

func (q *Queries) UpdateUserIsVerified(ctx context.Context, arg UpdateUserIsVerifiedParams) error {
	_, err := q.db.ExecContext(ctx, updateUserIsVerified, arg.IsVerified, arg.UpdatedAt, arg.ID)
	return err
}

const updateUserPassword = `-- name: UpdateUserPassword :exec
UPDATE users
SET password = $1,
    updated_at = $2
WHERE id = $3
`

type UpdateUserPasswordParams struct {
	Password  string
	UpdatedAt sql.NullTime
	ID        uuid.UUID
}

func (q *Queries) UpdateUserPassword(ctx context.Context, arg UpdateUserPasswordParams) error {
	_, err := q.db.ExecContext(ctx, updateUserPassword, arg.Password, arg.UpdatedAt, arg.ID)
	return err
}

const updateUserTokenExpiresAt = `-- name: UpdateUserTokenExpiresAt :exec
UPDATE users
SET token_expires_at = $1,
    updated_at = $2
WHERE id = $3
`

type UpdateUserTokenExpiresAtParams struct {
	TokenExpiresAt sql.NullTime
	UpdatedAt      sql.NullTime
	ID             uuid.UUID
}

func (q *Queries) UpdateUserTokenExpiresAt(ctx context.Context, arg UpdateUserTokenExpiresAtParams) error {
	_, err := q.db.ExecContext(ctx, updateUserTokenExpiresAt, arg.TokenExpiresAt, arg.UpdatedAt, arg.ID)
	return err
}

const updateUserVerifyToken = `-- name: UpdateUserVerifyToken :exec
UPDATE users
SET verify_token = $1,
    updated_at = $2
WHERE id = $3
`

type UpdateUserVerifyTokenParams struct {
	VerifyToken sql.NullString
	UpdatedAt   sql.NullTime
	ID          uuid.UUID
}

func (q *Queries) UpdateUserVerifyToken(ctx context.Context, arg UpdateUserVerifyTokenParams) error {
	_, err := q.db.ExecContext(ctx, updateUserVerifyToken, arg.VerifyToken, arg.UpdatedAt, arg.ID)
	return err
}
