// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: vocal_pattern.sql

package sqlcgen

import (
	"context"
	"database/sql"
)

const insertVocalPatterns = `-- name: InsertVocalPatterns :exec
INSERT INTO vocal_patterns (song_id, name)
VALUES ($1, $2)
`

type InsertVocalPatternsParams struct {
	SongID sql.NullInt32
	Name   sql.NullString
}

func (q *Queries) InsertVocalPatterns(ctx context.Context, arg InsertVocalPatternsParams) error {
	_, err := q.db.ExecContext(ctx, insertVocalPatterns, arg.SongID, arg.Name)
	return err
}
