// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: vocal_pattern_unit.sql

package sqlcgen

import (
	"context"
	"database/sql"
)

const insertVocalPatternUnits = `-- name: InsertVocalPatternUnits :exec
INSERT INTO vocal_pattern_units (vocal_pattern_id, unit_id)
VALUES ($1, $2)
`

type InsertVocalPatternUnitsParams struct {
	VocalPatternID sql.NullInt32
	UnitID         sql.NullInt32
}

func (q *Queries) InsertVocalPatternUnits(ctx context.Context, arg InsertVocalPatternUnitsParams) error {
	_, err := q.db.ExecContext(ctx, insertVocalPatternUnits, arg.VocalPatternID, arg.UnitID)
	return err
}
