// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: vocal_pattern_unit.sql

package sqlcgen

import (
	"context"
	"database/sql"
)

const insertVocalPatternUnit = `-- name: InsertVocalPatternUnit :one
INSERT INTO vocal_pattern_units (vocal_pattern_id, unit_id)
VALUES ($1, $2)
RETURNING id, vocal_pattern_id, unit_id
`

type InsertVocalPatternUnitParams struct {
	VocalPatternID sql.NullInt32
	UnitID         sql.NullInt32
}

func (q *Queries) InsertVocalPatternUnit(ctx context.Context, arg InsertVocalPatternUnitParams) (VocalPatternUnit, error) {
	row := q.db.QueryRowContext(ctx, insertVocalPatternUnit, arg.VocalPatternID, arg.UnitID)
	var i VocalPatternUnit
	err := row.Scan(&i.ID, &i.VocalPatternID, &i.UnitID)
	return i, err
}
