// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: vocal_pattern_singer.sql

package sqlcgen

import (
	"context"
	"database/sql"
)

const insertVocalPatternSingers = `-- name: InsertVocalPatternSingers :exec
INSERT INTO vocal_pattern_singers (vocal_pattern_id, singer_id, position)
VALUES ($1, $2, $3)
`

type InsertVocalPatternSingersParams struct {
	VocalPatternID sql.NullInt32
	SingerID       sql.NullInt32
	Position       sql.NullInt32
}

func (q *Queries) InsertVocalPatternSingers(ctx context.Context, arg InsertVocalPatternSingersParams) error {
	_, err := q.db.ExecContext(ctx, insertVocalPatternSingers, arg.VocalPatternID, arg.SingerID, arg.Position)
	return err
}
